// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sigalign
Rcpp::CharacterVector sigalign(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_sigalign(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sigalign(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// sigalign_stats
Rcpp::DataFrame sigalign_stats(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, int nthreads);
RcppExport SEXP _rad_sigalign_stats(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sigalign_stats(adapters, sequences, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// extract_blaze_barcode
Rcpp::DataFrame extract_blaze_barcode(std::string fastq_file, int print_every);
RcppExport SEXP _rad_extract_blaze_barcode(SEXP fastq_fileSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastq_file(fastq_fileSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(extract_blaze_barcode(fastq_file, print_every));
    return rcpp_result_gen;
END_RCPP
}
// extract_blaze_id_bc
void extract_blaze_id_bc(std::string fastq_file, std::string output_file, int print_every);
RcppExport SEXP _rad_extract_blaze_id_bc(SEXP fastq_fileSEXP, SEXP output_fileSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastq_file(fastq_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    extract_blaze_id_bc(fastq_file, output_file, print_every);
    return R_NilValue;
END_RCPP
}
// read_seqs_cpp
Rcpp::DataFrame read_seqs_cpp(std::string filename, std::string type, bool full_id, int max_reads);
RcppExport SEXP _rad_read_seqs_cpp(SEXP filenameSEXP, SEXP typeSEXP, SEXP full_idSEXP, SEXP max_readsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< bool >::type full_id(full_idSEXP);
    Rcpp::traits::input_parameter< int >::type max_reads(max_readsSEXP);
    rcpp_result_gen = Rcpp::wrap(read_seqs_cpp(filename, type, full_id, max_reads));
    return rcpp_result_gen;
END_RCPP
}
// stream_fastqas
SEXP stream_fastqas(SEXP fn, std::string type, bool full_id, int max_reads);
RcppExport SEXP _rad_stream_fastqas(SEXP fnSEXP, SEXP typeSEXP, SEXP full_idSEXP, SEXP max_readsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< bool >::type full_id(full_idSEXP);
    Rcpp::traits::input_parameter< int >::type max_reads(max_readsSEXP);
    rcpp_result_gen = Rcpp::wrap(stream_fastqas(fn, type, full_id, max_reads));
    return rcpp_result_gen;
END_RCPP
}
// masked_sigalign
Rcpp::CharacterVector masked_sigalign(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_masked_sigalign(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(masked_sigalign(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign
Rcpp::CharacterVector n_masked_sigalign(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_n_masked_sigalign(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_misalignment_cigar_string
Rcpp::DataFrame n_masked_misalignment_cigar_string(const std::string& input_path, Rcpp::CharacterVector adapters, int nthreads, int max_sequences, size_t chunk_size);
RcppExport SEXP _rad_n_masked_misalignment_cigar_string(SEXP input_pathSEXP, SEXP adaptersSEXP, SEXP nthreadsSEXP, SEXP max_sequencesSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type input_path(input_pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type max_sequences(max_sequencesSEXP);
    Rcpp::traits::input_parameter< size_t >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_misalignment_cigar_string(input_path, adapters, nthreads, max_sequences, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v2
Rcpp::CharacterVector n_masked_sigalign_v2(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_n_masked_sigalign_v2(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v2(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v3
Rcpp::CharacterVector n_masked_sigalign_v3(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads, int min_continuous_matches);
RcppExport SEXP _rad_n_masked_sigalign_v3(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP, SEXP min_continuous_matchesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type min_continuous_matches(min_continuous_matchesSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v3(adapters, sequences, ids, misalignment_threshold, nthreads, min_continuous_matches));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v4
Rcpp::CharacterVector n_masked_sigalign_v4(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_n_masked_sigalign_v4(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v4(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v5
Rcpp::CharacterVector n_masked_sigalign_v5(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_n_masked_sigalign_v5(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v5(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v6
Rcpp::CharacterVector n_masked_sigalign_v6(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads, bool verbose);
RcppExport SEXP _rad_n_masked_sigalign_v6(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v6(adapters, sequences, ids, misalignment_threshold, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v7
Rcpp::CharacterVector n_masked_sigalign_v7(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads, bool verbose);
RcppExport SEXP _rad_n_masked_sigalign_v7(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v7(adapters, sequences, ids, misalignment_threshold, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v8
Rcpp::CharacterVector n_masked_sigalign_v8(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads, bool verbose);
RcppExport SEXP _rad_n_masked_sigalign_v8(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v8(adapters, sequences, ids, misalignment_threshold, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v9
Rcpp::CharacterVector n_masked_sigalign_v9(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads, bool verbose);
RcppExport SEXP _rad_n_masked_sigalign_v9(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v9(adapters, sequences, ids, misalignment_threshold, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// n_masked_sigalign_v10
Rcpp::CharacterVector n_masked_sigalign_v10(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads, bool verbose);
RcppExport SEXP _rad_n_masked_sigalign_v10(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(n_masked_sigalign_v10(adapters, sequences, ids, misalignment_threshold, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cmv_consensusMatrix
NumericMatrix cmv_consensusMatrix(SEXP sequences);
RcppExport SEXP _rad_cmv_consensusMatrix(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(cmv_consensusMatrix(sequences));
    return rcpp_result_gen;
END_RCPP
}
// find_longest_matches
Rcpp::IntegerVector find_longest_matches(Rcpp::StringVector cigars);
RcppExport SEXP _rad_find_longest_matches(SEXP cigarsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type cigars(cigarsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_longest_matches(cigars));
    return rcpp_result_gen;
END_RCPP
}
// analyze_cigar_patterns
Rcpp::List analyze_cigar_patterns(Rcpp::StringVector cigars);
RcppExport SEXP _rad_analyze_cigar_patterns(SEXP cigarsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type cigars(cigarsSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_cigar_patterns(cigars));
    return rcpp_result_gen;
END_RCPP
}
// has_minimum_match_length
bool has_minimum_match_length(const std::string& cigar, int min_length);
RcppExport SEXP _rad_has_minimum_match_length(SEXP cigarSEXP, SEXP min_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type cigar(cigarSEXP);
    Rcpp::traits::input_parameter< int >::type min_length(min_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(has_minimum_match_length(cigar, min_length));
    return rcpp_result_gen;
END_RCPP
}
// edlib_search
List edlib_search(std::vector<std::string> queries, std::vector<std::string> targets, int max_distance, int num_threads);
RcppExport SEXP _rad_edlib_search(SEXP queriesSEXP, SEXP targetsSEXP, SEXP max_distanceSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(edlib_search(queries, targets, max_distance, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// stream_paf2mat
SEXP stream_paf2mat(std::string path, std::string target, double region_start, double region_end, int bin_bp, int min_mapq, int chunk_lines, bool symmetric, int threads, bool verbose);
RcppExport SEXP _rad_stream_paf2mat(SEXP pathSEXP, SEXP targetSEXP, SEXP region_startSEXP, SEXP region_endSEXP, SEXP bin_bpSEXP, SEXP min_mapqSEXP, SEXP chunk_linesSEXP, SEXP symmetricSEXP, SEXP threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type region_start(region_startSEXP);
    Rcpp::traits::input_parameter< double >::type region_end(region_endSEXP);
    Rcpp::traits::input_parameter< int >::type bin_bp(bin_bpSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_lines(chunk_linesSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(stream_paf2mat(path, target, region_start, region_end, bin_bp, min_mapq, chunk_lines, symmetric, threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// stream_paf2mat_anch
SEXP stream_paf2mat_anch(std::string path, std::string target, double region_start, double region_end, int bin_bp, int min_mapq, int min_anchor_bp, int chunk_lines, bool symmetric, int threads, bool verbose);
RcppExport SEXP _rad_stream_paf2mat_anch(SEXP pathSEXP, SEXP targetSEXP, SEXP region_startSEXP, SEXP region_endSEXP, SEXP bin_bpSEXP, SEXP min_mapqSEXP, SEXP min_anchor_bpSEXP, SEXP chunk_linesSEXP, SEXP symmetricSEXP, SEXP threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type region_start(region_startSEXP);
    Rcpp::traits::input_parameter< double >::type region_end(region_endSEXP);
    Rcpp::traits::input_parameter< int >::type bin_bp(bin_bpSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< int >::type min_anchor_bp(min_anchor_bpSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_lines(chunk_linesSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(stream_paf2mat_anch(path, target, region_start, region_end, bin_bp, min_mapq, min_anchor_bp, chunk_lines, symmetric, threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// splice_contacts_from_paf
SEXP splice_contacts_from_paf(std::string paf_path, std::string target, double region_start, double region_end, int bin_bp, int min_mapq, int chunk_lines, bool symmetric, int threads, bool verbose);
RcppExport SEXP _rad_splice_contacts_from_paf(SEXP paf_pathSEXP, SEXP targetSEXP, SEXP region_startSEXP, SEXP region_endSEXP, SEXP bin_bpSEXP, SEXP min_mapqSEXP, SEXP chunk_linesSEXP, SEXP symmetricSEXP, SEXP threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type paf_path(paf_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type region_start(region_startSEXP);
    Rcpp::traits::input_parameter< double >::type region_end(region_endSEXP);
    Rcpp::traits::input_parameter< int >::type bin_bp(bin_bpSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_lines(chunk_linesSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(splice_contacts_from_paf(paf_path, target, region_start, region_end, bin_bp, min_mapq, chunk_lines, symmetric, threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// splice_contacts_from_paf_dt
SEXP splice_contacts_from_paf_dt(DataFrame df, std::string target, double region_start, double region_end, int bin_bp, int min_mapq, int min_anchor_bp, int chunk_rows, bool symmetric, int threads, bool verbose, std::string col_tname, std::string col_tstart, std::string col_tend, std::string col_cg, std::string col_mapq, std::string col_strand);
RcppExport SEXP _rad_splice_contacts_from_paf_dt(SEXP dfSEXP, SEXP targetSEXP, SEXP region_startSEXP, SEXP region_endSEXP, SEXP bin_bpSEXP, SEXP min_mapqSEXP, SEXP min_anchor_bpSEXP, SEXP chunk_rowsSEXP, SEXP symmetricSEXP, SEXP threadsSEXP, SEXP verboseSEXP, SEXP col_tnameSEXP, SEXP col_tstartSEXP, SEXP col_tendSEXP, SEXP col_cgSEXP, SEXP col_mapqSEXP, SEXP col_strandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type region_start(region_startSEXP);
    Rcpp::traits::input_parameter< double >::type region_end(region_endSEXP);
    Rcpp::traits::input_parameter< int >::type bin_bp(bin_bpSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< int >::type min_anchor_bp(min_anchor_bpSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_rows(chunk_rowsSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::string >::type col_tname(col_tnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type col_tstart(col_tstartSEXP);
    Rcpp::traits::input_parameter< std::string >::type col_tend(col_tendSEXP);
    Rcpp::traits::input_parameter< std::string >::type col_cg(col_cgSEXP);
    Rcpp::traits::input_parameter< std::string >::type col_mapq(col_mapqSEXP);
    Rcpp::traits::input_parameter< std::string >::type col_strand(col_strandSEXP);
    rcpp_result_gen = Rcpp::wrap(splice_contacts_from_paf_dt(df, target, region_start, region_end, bin_bp, min_mapq, min_anchor_bp, chunk_rows, symmetric, threads, verbose, col_tname, col_tstart, col_tend, col_cg, col_mapq, col_strand));
    return rcpp_result_gen;
END_RCPP
}
// prep_read_layout_rcpp
void prep_read_layout_rcpp(const Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold, bool verbose);
RcppExport SEXP _rad_prep_read_layout_rcpp(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    prep_read_layout_rcpp(read_layout, misalignment_threshold, verbose);
    return R_NilValue;
END_RCPP
}
// generate_position_setup_test
void generate_position_setup_test(Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold);
RcppExport SEXP _rad_generate_position_setup_test(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    generate_position_setup_test(read_layout, misalignment_threshold);
    return R_NilValue;
END_RCPP
}
// sig_extraction_updated
Rcpp::DataFrame sig_extraction_updated(const Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold, Rcpp::DataFrame& df, const Rcpp::CharacterVector& processed_sigstrings, bool verbose);
RcppExport SEXP _rad_sig_extraction_updated(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP dfSEXP, SEXP processed_sigstringsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type processed_sigstrings(processed_sigstringsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sig_extraction_updated(read_layout, misalignment_threshold, df, processed_sigstrings, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sigrun
Rcpp::CharacterVector sigrun(const Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold, const Rcpp::StringVector& sigstrings, int nthreads, bool verbose);
RcppExport SEXP _rad_sigrun(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP sigstringsSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type sigstrings(sigstringsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sigrun(read_layout, misalignment_threshold, sigstrings, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// revcomp
Rcpp::StringVector revcomp(Rcpp::StringVector sequences);
RcppExport SEXP _rad_revcomp(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp(sequences));
    return rcpp_result_gen;
END_RCPP
}
// sequence_to_bits
Rcpp::NumericVector sequence_to_bits(Rcpp::StringVector sequences);
RcppExport SEXP _rad_sequence_to_bits(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sequence_to_bits(sequences));
    return rcpp_result_gen;
END_RCPP
}
// sequence_to_bitlist
List sequence_to_bitlist(Rcpp::StringVector sequences);
RcppExport SEXP _rad_sequence_to_bitlist(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sequence_to_bitlist(sequences));
    return rcpp_result_gen;
END_RCPP
}
// bits_to_sequence
Rcpp::StringVector bits_to_sequence(Rcpp::NumericVector input, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_bits_to_sequence(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(bits_to_sequence(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// bits_to_hex
StringVector bits_to_hex(Rcpp::NumericVector input, int sequence_length);
RcppExport SEXP _rad_bits_to_hex(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(bits_to_hex(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_bits
Rcpp::NumericVector revcomp_bits(Rcpp::NumericVector input, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_revcomp_bits(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_bits(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// hamming_distance_rcpp
int hamming_distance_rcpp(Rcpp::NumericVector a, Rcpp::NumericVector b);
RcppExport SEXP _rad_hamming_distance_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_distance_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// generate_quaternary_mutations
Rcpp::NumericVector generate_quaternary_mutations(Rcpp::NumericVector sequences, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_generate_quaternary_mutations(SEXP sequencesSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_quaternary_mutations(sequences, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// generate_recursive_quaternary_mutations
Rcpp::NumericVector generate_recursive_quaternary_mutations(Rcpp::NumericVector sequences, int mutation_rounds, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_generate_recursive_quaternary_mutations(SEXP sequencesSEXP, SEXP mutation_roundsSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_rounds(mutation_roundsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_recursive_quaternary_mutations(sequences, mutation_rounds, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// shift_barcodes
Rcpp::List shift_barcodes(SEXP sequences, int sequence_length, int max_shift, bool verbose);
RcppExport SEXP _rad_shift_barcodes(SEXP sequencesSEXP, SEXP sequence_lengthSEXP, SEXP max_shiftSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type sequence_length(sequence_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_barcodes(sequences, sequence_length, max_shift, verbose));
    return rcpp_result_gen;
END_RCPP
}
// barcode_correction_v3
Rcpp::DataFrame barcode_correction_v3(SEXP true_barcodes, SEXP invalid_barcodes, SEXP true_counts, SEXP invalid_counts, int mutation_rounds, int sequence_length, int nthread, int max_shift, int method, bool verbose);
RcppExport SEXP _rad_barcode_correction_v3(SEXP true_barcodesSEXP, SEXP invalid_barcodesSEXP, SEXP true_countsSEXP, SEXP invalid_countsSEXP, SEXP mutation_roundsSEXP, SEXP sequence_lengthSEXP, SEXP nthreadSEXP, SEXP max_shiftSEXP, SEXP methodSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type true_barcodes(true_barcodesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type invalid_barcodes(invalid_barcodesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type true_counts(true_countsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type invalid_counts(invalid_countsSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_rounds(mutation_roundsSEXP);
    Rcpp::traits::input_parameter< int >::type sequence_length(sequence_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(barcode_correction_v3(true_barcodes, invalid_barcodes, true_counts, invalid_counts, mutation_rounds, sequence_length, nthread, max_shift, method, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sigstream
void sigstream(const std::string& input_path, const std::string& sigstringsFilePath, Rcpp::CharacterVector adapters, const Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold, int chunkSize, int nthreads, const std::string& outputPath, bool write_fastq, bool compress, int max_sequences, int min_length, bool verbose);
RcppExport SEXP _rad_sigstream(SEXP input_pathSEXP, SEXP sigstringsFilePathSEXP, SEXP adaptersSEXP, SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP chunkSizeSEXP, SEXP nthreadsSEXP, SEXP outputPathSEXP, SEXP write_fastqSEXP, SEXP compressSEXP, SEXP max_sequencesSEXP, SEXP min_lengthSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type input_path(input_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sigstringsFilePath(sigstringsFilePathSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type chunkSize(chunkSizeSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type outputPath(outputPathSEXP);
    Rcpp::traits::input_parameter< bool >::type write_fastq(write_fastqSEXP);
    Rcpp::traits::input_parameter< bool >::type compress(compressSEXP);
    Rcpp::traits::input_parameter< int >::type max_sequences(max_sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type min_length(min_lengthSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    sigstream(input_path, sigstringsFilePath, adapters, read_layout, misalignment_threshold, chunkSize, nthreads, outputPath, write_fastq, compress, max_sequences, min_length, verbose);
    return R_NilValue;
END_RCPP
}
// misalignment_stream
Rcpp::DataFrame misalignment_stream(const std::string& input_path, Rcpp::CharacterVector adapters, int nthreads, int max_sequences, size_t chunk_size);
RcppExport SEXP _rad_misalignment_stream(SEXP input_pathSEXP, SEXP adaptersSEXP, SEXP nthreadsSEXP, SEXP max_sequencesSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type input_path(input_pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type max_sequences(max_sequencesSEXP);
    Rcpp::traits::input_parameter< size_t >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(misalignment_stream(input_path, adapters, nthreads, max_sequences, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// tabulate_variable_sequences
void tabulate_variable_sequences(const std::vector<std::string>& input_files, const std::string& output_prefix, const std::vector<std::string>& identity_elements, bool compress, size_t batch_size);
RcppExport SEXP _rad_tabulate_variable_sequences(SEXP input_filesSEXP, SEXP output_prefixSEXP, SEXP identity_elementsSEXP, SEXP compressSEXP, SEXP batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input_files(input_filesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_prefix(output_prefixSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type identity_elements(identity_elementsSEXP);
    Rcpp::traits::input_parameter< bool >::type compress(compressSEXP);
    Rcpp::traits::input_parameter< size_t >::type batch_size(batch_sizeSEXP);
    tabulate_variable_sequences(input_files, output_prefix, identity_elements, compress, batch_size);
    return R_NilValue;
END_RCPP
}
// tabulate_sigs
void tabulate_sigs(const std::string& file_path, const std::string& output_prefix, int chunk_size, int max_sequences, int nthreads, bool compress, const std::string& output_type);
RcppExport SEXP _rad_tabulate_sigs(SEXP file_pathSEXP, SEXP output_prefixSEXP, SEXP chunk_sizeSEXP, SEXP max_sequencesSEXP, SEXP nthreadsSEXP, SEXP compressSEXP, SEXP output_typeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_prefix(output_prefixSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_sequences(max_sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type compress(compressSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_type(output_typeSEXP);
    tabulate_sigs(file_path, output_prefix, chunk_size, max_sequences, nthreads, compress, output_type);
    return R_NilValue;
END_RCPP
}
// fastq_correction
Rcpp::DataFrame fastq_correction(std::string input_file, std::string output_file, Rcpp::StringVector incorrect_bcs, Rcpp::StringVector correct_bcs, std::string barcode_id, int chunk_size, int print_freq, int nthreads, int downsample);
RcppExport SEXP _rad_fastq_correction(SEXP input_fileSEXP, SEXP output_fileSEXP, SEXP incorrect_bcsSEXP, SEXP correct_bcsSEXP, SEXP barcode_idSEXP, SEXP chunk_sizeSEXP, SEXP print_freqSEXP, SEXP nthreadsSEXP, SEXP downsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type incorrect_bcs(incorrect_bcsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type correct_bcs(correct_bcsSEXP);
    Rcpp::traits::input_parameter< std::string >::type barcode_id(barcode_idSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type print_freq(print_freqSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type downsample(downsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(fastq_correction(input_file, output_file, incorrect_bcs, correct_bcs, barcode_id, chunk_size, print_freq, nthreads, downsample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rad_sigalign", (DL_FUNC) &_rad_sigalign, 5},
    {"_rad_sigalign_stats", (DL_FUNC) &_rad_sigalign_stats, 3},
    {"_rad_extract_blaze_barcode", (DL_FUNC) &_rad_extract_blaze_barcode, 2},
    {"_rad_extract_blaze_id_bc", (DL_FUNC) &_rad_extract_blaze_id_bc, 3},
    {"_rad_read_seqs_cpp", (DL_FUNC) &_rad_read_seqs_cpp, 4},
    {"_rad_stream_fastqas", (DL_FUNC) &_rad_stream_fastqas, 4},
    {"_rad_masked_sigalign", (DL_FUNC) &_rad_masked_sigalign, 5},
    {"_rad_n_masked_sigalign", (DL_FUNC) &_rad_n_masked_sigalign, 5},
    {"_rad_n_masked_misalignment_cigar_string", (DL_FUNC) &_rad_n_masked_misalignment_cigar_string, 5},
    {"_rad_n_masked_sigalign_v2", (DL_FUNC) &_rad_n_masked_sigalign_v2, 5},
    {"_rad_n_masked_sigalign_v3", (DL_FUNC) &_rad_n_masked_sigalign_v3, 6},
    {"_rad_n_masked_sigalign_v4", (DL_FUNC) &_rad_n_masked_sigalign_v4, 5},
    {"_rad_n_masked_sigalign_v5", (DL_FUNC) &_rad_n_masked_sigalign_v5, 5},
    {"_rad_n_masked_sigalign_v6", (DL_FUNC) &_rad_n_masked_sigalign_v6, 6},
    {"_rad_n_masked_sigalign_v7", (DL_FUNC) &_rad_n_masked_sigalign_v7, 6},
    {"_rad_n_masked_sigalign_v8", (DL_FUNC) &_rad_n_masked_sigalign_v8, 6},
    {"_rad_n_masked_sigalign_v9", (DL_FUNC) &_rad_n_masked_sigalign_v9, 6},
    {"_rad_n_masked_sigalign_v10", (DL_FUNC) &_rad_n_masked_sigalign_v10, 6},
    {"_rad_cmv_consensusMatrix", (DL_FUNC) &_rad_cmv_consensusMatrix, 1},
    {"_rad_find_longest_matches", (DL_FUNC) &_rad_find_longest_matches, 1},
    {"_rad_analyze_cigar_patterns", (DL_FUNC) &_rad_analyze_cigar_patterns, 1},
    {"_rad_has_minimum_match_length", (DL_FUNC) &_rad_has_minimum_match_length, 2},
    {"_rad_edlib_search", (DL_FUNC) &_rad_edlib_search, 4},
    {"_rad_stream_paf2mat", (DL_FUNC) &_rad_stream_paf2mat, 10},
    {"_rad_stream_paf2mat_anch", (DL_FUNC) &_rad_stream_paf2mat_anch, 11},
    {"_rad_splice_contacts_from_paf", (DL_FUNC) &_rad_splice_contacts_from_paf, 10},
    {"_rad_splice_contacts_from_paf_dt", (DL_FUNC) &_rad_splice_contacts_from_paf_dt, 17},
    {"_rad_prep_read_layout_rcpp", (DL_FUNC) &_rad_prep_read_layout_rcpp, 3},
    {"_rad_generate_position_setup_test", (DL_FUNC) &_rad_generate_position_setup_test, 2},
    {"_rad_sig_extraction_updated", (DL_FUNC) &_rad_sig_extraction_updated, 5},
    {"_rad_sigrun", (DL_FUNC) &_rad_sigrun, 5},
    {"_rad_revcomp", (DL_FUNC) &_rad_revcomp, 1},
    {"_rad_sequence_to_bits", (DL_FUNC) &_rad_sequence_to_bits, 1},
    {"_rad_sequence_to_bitlist", (DL_FUNC) &_rad_sequence_to_bitlist, 1},
    {"_rad_bits_to_sequence", (DL_FUNC) &_rad_bits_to_sequence, 2},
    {"_rad_bits_to_hex", (DL_FUNC) &_rad_bits_to_hex, 2},
    {"_rad_revcomp_bits", (DL_FUNC) &_rad_revcomp_bits, 2},
    {"_rad_hamming_distance_rcpp", (DL_FUNC) &_rad_hamming_distance_rcpp, 2},
    {"_rad_generate_quaternary_mutations", (DL_FUNC) &_rad_generate_quaternary_mutations, 2},
    {"_rad_generate_recursive_quaternary_mutations", (DL_FUNC) &_rad_generate_recursive_quaternary_mutations, 3},
    {"_rad_shift_barcodes", (DL_FUNC) &_rad_shift_barcodes, 4},
    {"_rad_barcode_correction_v3", (DL_FUNC) &_rad_barcode_correction_v3, 10},
    {"_rad_sigstream", (DL_FUNC) &_rad_sigstream, 13},
    {"_rad_misalignment_stream", (DL_FUNC) &_rad_misalignment_stream, 5},
    {"_rad_tabulate_variable_sequences", (DL_FUNC) &_rad_tabulate_variable_sequences, 5},
    {"_rad_tabulate_sigs", (DL_FUNC) &_rad_tabulate_sigs, 7},
    {"_rad_fastq_correction", (DL_FUNC) &_rad_fastq_correction, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_rad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
