// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// packed_reads_build_cpp
SEXP packed_reads_build_cpp(Rcpp::CharacterVector ids, Rcpp::CharacterVector sequences, SEXP qualities_sexp, SEXP comments_sexp, int phred_offset);
RcppExport SEXP _rrad_packed_reads_build_cpp(SEXP idsSEXP, SEXP sequencesSEXP, SEXP qualities_sexpSEXP, SEXP comments_sexpSEXP, SEXP phred_offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type qualities_sexp(qualities_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type comments_sexp(comments_sexpSEXP);
    Rcpp::traits::input_parameter< int >::type phred_offset(phred_offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_reads_build_cpp(ids, sequences, qualities_sexp, comments_sexp, phred_offset));
    return rcpp_result_gen;
END_RCPP
}
// packed_id_decode_cpp
Rcpp::CharacterVector packed_id_decode_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_id_decode_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_id_decode_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_sequence_decode_cpp
Rcpp::CharacterVector packed_sequence_decode_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_sequence_decode_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_sequence_decode_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_quality_decode_cpp
Rcpp::CharacterVector packed_quality_decode_cpp(SEXP handles, int phred_offset);
RcppExport SEXP _rrad_packed_quality_decode_cpp(SEXP handlesSEXP, SEXP phred_offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    Rcpp::traits::input_parameter< int >::type phred_offset(phred_offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_quality_decode_cpp(handles, phred_offset));
    return rcpp_result_gen;
END_RCPP
}
// packed_quality_values_cpp
Rcpp::List packed_quality_values_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_quality_values_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_quality_values_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_quality_mean_cpp
Rcpp::NumericVector packed_quality_mean_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_quality_mean_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_quality_mean_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_quality_min_cpp
Rcpp::IntegerVector packed_quality_min_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_quality_min_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_quality_min_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_quality_fraction_cpp
Rcpp::NumericVector packed_quality_fraction_cpp(SEXP handles, int threshold);
RcppExport SEXP _rrad_packed_quality_fraction_cpp(SEXP handlesSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_quality_fraction_cpp(handles, threshold));
    return rcpp_result_gen;
END_RCPP
}
// packed_sequence_format_cpp
Rcpp::CharacterVector packed_sequence_format_cpp(SEXP handles, int width);
RcppExport SEXP _rrad_packed_sequence_format_cpp(SEXP handlesSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_sequence_format_cpp(handles, width));
    return rcpp_result_gen;
END_RCPP
}
// packed_quality_format_cpp
Rcpp::CharacterVector packed_quality_format_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_quality_format_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_quality_format_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_store_stats_cpp
Rcpp::List packed_store_stats_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_store_stats_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_store_stats_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_validate_handles_cpp
bool packed_validate_handles_cpp(SEXP id_handles, SEXP sequence_handles, SEXP quality_handles, SEXP comment_handles);
RcppExport SEXP _rrad_packed_validate_handles_cpp(SEXP id_handlesSEXP, SEXP sequence_handlesSEXP, SEXP quality_handlesSEXP, SEXP comment_handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type id_handles(id_handlesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sequence_handles(sequence_handlesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type quality_handles(quality_handlesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type comment_handles(comment_handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_validate_handles_cpp(id_handles, sequence_handles, quality_handles, comment_handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_handle_is_na_cpp
Rcpp::LogicalVector packed_handle_is_na_cpp(SEXP handles);
RcppExport SEXP _rrad_packed_handle_is_na_cpp(SEXP handlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handles(handlesSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_handle_is_na_cpp(handles));
    return rcpp_result_gen;
END_RCPP
}
// packed_fastq_stream_open_cpp
SEXP packed_fastq_stream_open_cpp(std::string path, int phred_offset, bool keep_comment);
RcppExport SEXP _rrad_packed_fastq_stream_open_cpp(SEXP pathSEXP, SEXP phred_offsetSEXP, SEXP keep_commentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type phred_offset(phred_offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_comment(keep_commentSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_fastq_stream_open_cpp(path, phred_offset, keep_comment));
    return rcpp_result_gen;
END_RCPP
}
// packed_fastq_stream_next_cpp
SEXP packed_fastq_stream_next_cpp(SEXP pointer, int chunk_size);
RcppExport SEXP _rrad_packed_fastq_stream_next_cpp(SEXP pointerSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_fastq_stream_next_cpp(pointer, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// packed_fastq_stream_state_cpp
Rcpp::LogicalVector packed_fastq_stream_state_cpp(SEXP pointer);
RcppExport SEXP _rrad_packed_fastq_stream_state_cpp(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(packed_fastq_stream_state_cpp(pointer));
    return rcpp_result_gen;
END_RCPP
}
// packed_fastq_stream_close_cpp
void packed_fastq_stream_close_cpp(SEXP pointer);
RcppExport SEXP _rrad_packed_fastq_stream_close_cpp(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    packed_fastq_stream_close_cpp(pointer);
    return R_NilValue;
END_RCPP
}
// packed_write_fastq_cpp
void packed_write_fastq_cpp(SEXP id_handles, SEXP sequence_handles, SEXP quality_handles, SEXP comment_handles, std::string path, int phred_offset, bool append);
RcppExport SEXP _rrad_packed_write_fastq_cpp(SEXP id_handlesSEXP, SEXP sequence_handlesSEXP, SEXP quality_handlesSEXP, SEXP comment_handlesSEXP, SEXP pathSEXP, SEXP phred_offsetSEXP, SEXP appendSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type id_handles(id_handlesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sequence_handles(sequence_handlesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type quality_handles(quality_handlesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type comment_handles(comment_handlesSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type phred_offset(phred_offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type append(appendSEXP);
    packed_write_fastq_cpp(id_handles, sequence_handles, quality_handles, comment_handles, path, phred_offset, append);
    return R_NilValue;
END_RCPP
}
// rad_core_info_cpp
Rcpp::List rad_core_info_cpp();
RcppExport SEXP _rrad_rad_core_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rad_core_info_cpp());
    return rcpp_result_gen;
END_RCPP
}
// rad_any_file_equivalent_cpp
bool rad_any_file_equivalent_cpp(Rcpp::CharacterVector candidates, Rcpp::CharacterVector protected_paths);
RcppExport SEXP _rrad_rad_any_file_equivalent_cpp(SEXP candidatesSEXP, SEXP protected_pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type protected_paths(protected_pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(rad_any_file_equivalent_cpp(candidates, protected_paths));
    return rcpp_result_gen;
END_RCPP
}
// rad_scan_wl_cpp
Rcpp::List rad_scan_wl_cpp(Rcpp::List options);
RcppExport SEXP _rrad_rad_scan_wl_cpp(SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rad_scan_wl_cpp(options));
    return rcpp_result_gen;
END_RCPP
}
// rad_reformat_cpp
SEXP rad_reformat_cpp(Rcpp::List options);
RcppExport SEXP _rrad_rad_reformat_cpp(SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    // Deliberately return the already-built SEXP directly. Generic Rcpp
    // wrapping/preservation can allocate after native publication.
    return rad_reformat_cpp(options);
END_RCPP
}
// rad_demux_cpp
Rcpp::List rad_demux_cpp(Rcpp::List options);
RcppExport SEXP _rrad_rad_demux_cpp(SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rad_demux_cpp(options));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rrad_packed_reads_build_cpp", (DL_FUNC) &_rrad_packed_reads_build_cpp, 5},
    {"_rrad_packed_id_decode_cpp", (DL_FUNC) &_rrad_packed_id_decode_cpp, 1},
    {"_rrad_packed_sequence_decode_cpp", (DL_FUNC) &_rrad_packed_sequence_decode_cpp, 1},
    {"_rrad_packed_quality_decode_cpp", (DL_FUNC) &_rrad_packed_quality_decode_cpp, 2},
    {"_rrad_packed_quality_values_cpp", (DL_FUNC) &_rrad_packed_quality_values_cpp, 1},
    {"_rrad_packed_quality_mean_cpp", (DL_FUNC) &_rrad_packed_quality_mean_cpp, 1},
    {"_rrad_packed_quality_min_cpp", (DL_FUNC) &_rrad_packed_quality_min_cpp, 1},
    {"_rrad_packed_quality_fraction_cpp", (DL_FUNC) &_rrad_packed_quality_fraction_cpp, 2},
    {"_rrad_packed_sequence_format_cpp", (DL_FUNC) &_rrad_packed_sequence_format_cpp, 2},
    {"_rrad_packed_quality_format_cpp", (DL_FUNC) &_rrad_packed_quality_format_cpp, 1},
    {"_rrad_packed_store_stats_cpp", (DL_FUNC) &_rrad_packed_store_stats_cpp, 1},
    {"_rrad_packed_validate_handles_cpp", (DL_FUNC) &_rrad_packed_validate_handles_cpp, 4},
    {"_rrad_packed_handle_is_na_cpp", (DL_FUNC) &_rrad_packed_handle_is_na_cpp, 1},
    {"_rrad_packed_fastq_stream_open_cpp", (DL_FUNC) &_rrad_packed_fastq_stream_open_cpp, 3},
    {"_rrad_packed_fastq_stream_next_cpp", (DL_FUNC) &_rrad_packed_fastq_stream_next_cpp, 2},
    {"_rrad_packed_fastq_stream_state_cpp", (DL_FUNC) &_rrad_packed_fastq_stream_state_cpp, 1},
    {"_rrad_packed_fastq_stream_close_cpp", (DL_FUNC) &_rrad_packed_fastq_stream_close_cpp, 1},
    {"_rrad_packed_write_fastq_cpp", (DL_FUNC) &_rrad_packed_write_fastq_cpp, 7},
    {"_rrad_rad_core_info_cpp", (DL_FUNC) &_rrad_rad_core_info_cpp, 0},
    {"_rrad_rad_any_file_equivalent_cpp", (DL_FUNC) &_rrad_rad_any_file_equivalent_cpp, 2},
    {"_rrad_rad_scan_wl_cpp", (DL_FUNC) &_rrad_rad_scan_wl_cpp, 1},
    {"_rrad_rad_reformat_cpp", (DL_FUNC) &_rrad_rad_reformat_cpp, 1},
    {"_rrad_rad_demux_cpp", (DL_FUNC) &_rrad_rad_demux_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rrad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
