# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigalign <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_sigalign`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

sigalign_stats <- function(adapters, sequences, nthreads = 1L) {
    .Call(`_rad_sigalign_stats`, adapters, sequences, nthreads)
}

extract_blaze_barcode <- function(fastq_file, print_every = 10000L) {
    .Call(`_rad_extract_blaze_barcode`, fastq_file, print_every)
}

extract_blaze_id_bc <- function(fastq_file, output_file, print_every = 10000L) {
    invisible(.Call(`_rad_extract_blaze_id_bc`, fastq_file, output_file, print_every))
}

read_seqs_cpp <- function(filename, type, full_id = FALSE, max_reads = -1L) {
    .Call(`_rad_read_seqs_cpp`, filename, type, full_id, max_reads)
}

stream_fastqas <- function(fn, type = "fq", full_id = FALSE, max_reads = -1L) {
    .Call(`_rad_stream_fastqas`, fn, type, full_id, max_reads)
}

masked_sigalign <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_masked_sigalign`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

n_masked_sigalign <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_n_masked_sigalign`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

n_masked_misalignment_cigar_string <- function(input_path, adapters, nthreads = 1L, max_sequences = 500000L, chunk_size = 50000L) {
    .Call(`_rad_n_masked_misalignment_cigar_string`, input_path, adapters, nthreads, max_sequences, chunk_size)
}

n_masked_sigalign_v2 <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_n_masked_sigalign_v2`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

n_masked_sigalign_v3 <- function(adapters, sequences, ids, misalignment_threshold, nthreads, min_continuous_matches = 8L) {
    .Call(`_rad_n_masked_sigalign_v3`, adapters, sequences, ids, misalignment_threshold, nthreads, min_continuous_matches)
}

n_masked_sigalign_v4 <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_n_masked_sigalign_v4`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

n_masked_sigalign_v5 <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_n_masked_sigalign_v5`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

n_masked_sigalign_v6 <- function(adapters, sequences, ids, misalignment_threshold, nthreads, verbose = FALSE) {
    .Call(`_rad_n_masked_sigalign_v6`, adapters, sequences, ids, misalignment_threshold, nthreads, verbose)
}

n_masked_sigalign_v7 <- function(adapters, sequences, ids, misalignment_threshold, nthreads, verbose = FALSE) {
    .Call(`_rad_n_masked_sigalign_v7`, adapters, sequences, ids, misalignment_threshold, nthreads, verbose)
}

n_masked_sigalign_v8 <- function(adapters, sequences, ids, misalignment_threshold, nthreads, verbose = FALSE) {
    .Call(`_rad_n_masked_sigalign_v8`, adapters, sequences, ids, misalignment_threshold, nthreads, verbose)
}

n_masked_sigalign_v9 <- function(adapters, sequences, ids, misalignment_threshold, nthreads, verbose = FALSE) {
    .Call(`_rad_n_masked_sigalign_v9`, adapters, sequences, ids, misalignment_threshold, nthreads, verbose)
}

n_masked_sigalign_v10 <- function(adapters, sequences, ids, misalignment_threshold, nthreads, verbose = FALSE) {
    .Call(`_rad_n_masked_sigalign_v10`, adapters, sequences, ids, misalignment_threshold, nthreads, verbose)
}

cmv_consensusMatrix <- function(sequences) {
    .Call(`_rad_cmv_consensusMatrix`, sequences)
}

find_longest_matches <- function(cigars) {
    .Call(`_rad_find_longest_matches`, cigars)
}

analyze_cigar_patterns <- function(cigars) {
    .Call(`_rad_analyze_cigar_patterns`, cigars)
}

has_minimum_match_length <- function(cigar, min_length) {
    .Call(`_rad_has_minimum_match_length`, cigar, min_length)
}

edlib_search <- function(queries, targets, max_distance = 3L, num_threads = 0L) {
    .Call(`_rad_edlib_search`, queries, targets, max_distance, num_threads)
}

stream_paf2mat <- function(path, target = "", region_start = 1.0, region_end = 0.0, bin_bp = 250L, min_mapq = 0L, chunk_lines = 200000L, symmetric = TRUE, threads = 0L, verbose = FALSE) {
    .Call(`_rad_stream_paf2mat`, path, target, region_start, region_end, bin_bp, min_mapq, chunk_lines, symmetric, threads, verbose)
}

stream_paf2mat_anch <- function(path, target = "", region_start = 1.0, region_end = 0.0, bin_bp = 250L, min_mapq = 0L, min_anchor_bp = 1L, chunk_lines = 200000L, symmetric = TRUE, threads = 0L, verbose = FALSE) {
    .Call(`_rad_stream_paf2mat_anch`, path, target, region_start, region_end, bin_bp, min_mapq, min_anchor_bp, chunk_lines, symmetric, threads, verbose)
}

splice_contacts_from_paf <- function(paf_path, target = "", region_start = 1.0, region_end = 0.0, bin_bp = 250L, min_mapq = 0L, chunk_lines = 200000L, symmetric = TRUE, threads = 0L, verbose = FALSE) {
    .Call(`_rad_splice_contacts_from_paf`, paf_path, target, region_start, region_end, bin_bp, min_mapq, chunk_lines, symmetric, threads, verbose)
}

splice_contacts_from_paf_dt <- function(df, target = "", region_start = 1.0, region_end = 0.0, bin_bp = 250L, min_mapq = 0L, min_anchor_bp = 1L, chunk_rows = 1000000L, symmetric = TRUE, threads = 0L, verbose = FALSE, col_tname = "tname", col_tstart = "tstart", col_tend = "tend", col_cg = "cg", col_mapq = "mapq", col_strand = "strand") {
    .Call(`_rad_splice_contacts_from_paf_dt`, df, target, region_start, region_end, bin_bp, min_mapq, min_anchor_bp, chunk_rows, symmetric, threads, verbose, col_tname, col_tstart, col_tend, col_cg, col_mapq, col_strand)
}

prep_read_layout_rcpp <- function(read_layout, misalignment_threshold, verbose) {
    invisible(.Call(`_rad_prep_read_layout_rcpp`, read_layout, misalignment_threshold, verbose))
}

generate_position_setup_test <- function(read_layout, misalignment_threshold) {
    invisible(.Call(`_rad_generate_position_setup_test`, read_layout, misalignment_threshold))
}

sig_extraction_updated <- function(read_layout, misalignment_threshold, df, processed_sigstrings, verbose) {
    .Call(`_rad_sig_extraction_updated`, read_layout, misalignment_threshold, df, processed_sigstrings, verbose)
}

sigrun <- function(read_layout, misalignment_threshold, sigstrings, nthreads = 1L, verbose = FALSE) {
    .Call(`_rad_sigrun`, read_layout, misalignment_threshold, sigstrings, nthreads, verbose)
}

revcomp <- function(sequences) {
    .Call(`_rad_revcomp`, sequences)
}

sequence_to_bits <- function(sequences) {
    .Call(`_rad_sequence_to_bits`, sequences)
}

sequence_to_bitlist <- function(sequences) {
    .Call(`_rad_sequence_to_bitlist`, sequences)
}

bits_to_sequence <- function(input, sequence_length = 16L) {
    .Call(`_rad_bits_to_sequence`, input, sequence_length)
}

bits_to_hex <- function(input, sequence_length = 16L) {
    .Call(`_rad_bits_to_hex`, input, sequence_length)
}

revcomp_bits <- function(input, sequence_length = 16L) {
    .Call(`_rad_revcomp_bits`, input, sequence_length)
}

hamming_distance_rcpp <- function(a, b) {
    .Call(`_rad_hamming_distance_rcpp`, a, b)
}

generate_quaternary_mutations <- function(sequences, sequence_length = 32L) {
    .Call(`_rad_generate_quaternary_mutations`, sequences, sequence_length)
}

generate_recursive_quaternary_mutations <- function(sequences, mutation_rounds = 2L, sequence_length = 32L) {
    .Call(`_rad_generate_recursive_quaternary_mutations`, sequences, mutation_rounds, sequence_length)
}

shift_barcodes <- function(sequences, sequence_length, max_shift = 2L, verbose = FALSE) {
    .Call(`_rad_shift_barcodes`, sequences, sequence_length, max_shift, verbose)
}

barcode_correction_v3 <- function(true_barcodes, invalid_barcodes, true_counts, invalid_counts, mutation_rounds = 3L, sequence_length = 16L, nthread = 1L, max_shift = 3L, method = 2L, verbose = FALSE) {
    .Call(`_rad_barcode_correction_v3`, true_barcodes, invalid_barcodes, true_counts, invalid_counts, mutation_rounds, sequence_length, nthread, max_shift, method, verbose)
}

sigstream <- function(input_path, sigstringsFilePath, adapters, read_layout, misalignment_threshold, chunkSize, nthreads, outputPath, write_fastq = TRUE, compress = TRUE, max_sequences = -1L, min_length = 100L, verbose = FALSE) {
    invisible(.Call(`_rad_sigstream`, input_path, sigstringsFilePath, adapters, read_layout, misalignment_threshold, chunkSize, nthreads, outputPath, write_fastq, compress, max_sequences, min_length, verbose))
}

misalignment_stream <- function(input_path, adapters, nthreads = 1L, max_sequences = 500000L, chunk_size = 50000L) {
    .Call(`_rad_misalignment_stream`, input_path, adapters, nthreads, max_sequences, chunk_size)
}

tabulate_variable_sequences <- function(input_files, output_prefix, identity_elements, compress = TRUE, batch_size = 50000L) {
    invisible(.Call(`_rad_tabulate_variable_sequences`, input_files, output_prefix, identity_elements, compress, batch_size))
}

tabulate_sigs <- function(file_path, output_prefix, chunk_size = 50000L, max_sequences = -1L, nthreads = 1L, compress = TRUE, output_type = "summary") {
    invisible(.Call(`_rad_tabulate_sigs`, file_path, output_prefix, chunk_size, max_sequences, nthreads, compress, output_type))
}

fastq_correction <- function(input_file, output_file, incorrect_bcs, correct_bcs, barcode_id = "barcode", chunk_size = 50000L, print_freq = 10000L, nthreads = 4L, downsample = -1L) {
    .Call(`_rad_fastq_correction`, input_file, output_file, incorrect_bcs, correct_bcs, barcode_id, chunk_size, print_freq, nthreads, downsample)
}

