# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

packed_reads_build_cpp <- function(ids, sequences, qualities_sexp = NULL, comments_sexp = NULL, phred_offset = 33L) {
    .Call(`_rrad_packed_reads_build_cpp`, ids, sequences, qualities_sexp, comments_sexp, phred_offset)
}

packed_id_decode_cpp <- function(handles) {
    .Call(`_rrad_packed_id_decode_cpp`, handles)
}

packed_sequence_decode_cpp <- function(handles) {
    .Call(`_rrad_packed_sequence_decode_cpp`, handles)
}

packed_quality_decode_cpp <- function(handles, phred_offset = 33L) {
    .Call(`_rrad_packed_quality_decode_cpp`, handles, phred_offset)
}

packed_quality_values_cpp <- function(handles) {
    .Call(`_rrad_packed_quality_values_cpp`, handles)
}

packed_quality_mean_cpp <- function(handles) {
    .Call(`_rrad_packed_quality_mean_cpp`, handles)
}

packed_quality_min_cpp <- function(handles) {
    .Call(`_rrad_packed_quality_min_cpp`, handles)
}

packed_quality_fraction_cpp <- function(handles, threshold) {
    .Call(`_rrad_packed_quality_fraction_cpp`, handles, threshold)
}

packed_sequence_format_cpp <- function(handles, width = 24L) {
    .Call(`_rrad_packed_sequence_format_cpp`, handles, width)
}

packed_quality_format_cpp <- function(handles) {
    .Call(`_rrad_packed_quality_format_cpp`, handles)
}

packed_store_stats_cpp <- function(handles) {
    .Call(`_rrad_packed_store_stats_cpp`, handles)
}

packed_validate_handles_cpp <- function(id_handles, sequence_handles, quality_handles, comment_handles = NULL) {
    .Call(`_rrad_packed_validate_handles_cpp`, id_handles, sequence_handles, quality_handles, comment_handles)
}

packed_handle_is_na_cpp <- function(handles) {
    .Call(`_rrad_packed_handle_is_na_cpp`, handles)
}

packed_fastq_stream_open_cpp <- function(path, phred_offset = 33L, keep_comment = TRUE) {
    .Call(`_rrad_packed_fastq_stream_open_cpp`, path, phred_offset, keep_comment)
}

packed_fastq_stream_next_cpp <- function(pointer, chunk_size = 50000L) {
    .Call(`_rrad_packed_fastq_stream_next_cpp`, pointer, chunk_size)
}

packed_fastq_stream_state_cpp <- function(pointer) {
    .Call(`_rrad_packed_fastq_stream_state_cpp`, pointer)
}

packed_fastq_stream_close_cpp <- function(pointer) {
    invisible(.Call(`_rrad_packed_fastq_stream_close_cpp`, pointer))
}

packed_write_fastq_cpp <- function(id_handles, sequence_handles, quality_handles, comment_handles, path, phred_offset = 33L, append = FALSE) {
    invisible(.Call(`_rrad_packed_write_fastq_cpp`, id_handles, sequence_handles, quality_handles, comment_handles, path, phred_offset, append))
}

rad_core_info_cpp <- function() {
    .Call(`_rrad_rad_core_info_cpp`)
}

.rad_any_file_equivalent_cpp <- function(candidates, protected_paths) {
    .Call(`_rrad_rad_any_file_equivalent_cpp`, candidates, protected_paths)
}

.rad_scan_wl_cpp <- function(options) {
    .Call(`_rrad_rad_scan_wl_cpp`, options)
}

.rad_reformat_cpp <- function(options) {
    .Call(`_rrad_rad_reformat_cpp`, options)
}

rad_demux_cpp <- function(options) {
    .Call(`_rrad_rad_demux_cpp`, options)
}

